---
title: Read Below
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: irenealgi@gmail.com
description: Literature, publishing & many other matters.
url: http://readbelow.net
image: "/assets/images/writing.jpg"
markdown: kramdown
permalink: :title
sass:
  style: :compressed
  sass_dir: assets/sass
paginate: 7
gems:
- jekyll-paginate
exclude:
- Guardfile
- ".gitignore"
- README.md
